### ISSUE TITLE
Gameplay todo list

### ISSUE THREAD

**Issue by Lubba-64** [SoulShardStudios/bevy_pixelmap#4]
- [ ] Import assets
 - [ ] Get player character animating
 - [ ] Add collision
 - [ ] UI for switching brushes
 - [ ] UI for switching colors
